from typing import List, Optional
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from aiserver.core.session import SessionManager
from aiserver.core.context import ContextOptimizer

class JuChatMessageHistory(BaseChatMessageHistory):
    """
    Adapter class to connect LangChain's history interface with JuServer's SessionManager.
    """
    def __init__(self, session_manager: SessionManager, notebook_id: str, cell_id: str, current_code: str = "", optimizer: Optional[ContextOptimizer] = None):
        self.session_manager = session_manager
        self.notebook_id = notebook_id
        self.cell_id = cell_id
        self.current_code = current_code
        self.optimizer = optimizer
        self._pending_user_message: Optional[str] = None
        
    @property
    def messages(self) -> List[BaseMessage]:
        """Retrieve messages from SessionManager."""
        history = self.session_manager.get_history(self.notebook_id, self.cell_id)
        if self.optimizer:
            return self.optimizer.optimize_history(history)
        return history

    def add_messages(self, messages: List[BaseMessage]) -> None:
        """
        Add messages to the session. 
        
        Since SessionManager saves 'Interactions' (User + AI pair), 
        we buffer the HumanMessage and save when we encounter an AIMessage.
        """
        for message in messages:
            if isinstance(message, HumanMessage):
                self._pending_user_message = message.content
            elif isinstance(message, AIMessage):
                # If we have an AI message, we try to save an interaction
                intent = self._pending_user_message if self._pending_user_message else "Continued Conversation"
                
                self.session_manager.save_interaction(
                    notebook_id=self.notebook_id,
                    cell_id=self.cell_id,
                    intent=intent,
                    current_code=self.current_code,
                    suggestion=message.content,
                    explanation="Generated by LangChain"
                )
                # Reset pending message after saving
                self._pending_user_message = None

    def clear(self) -> None:
        """Clear session history."""
        # TODO: Implement clear method in SessionManager if needed.
        # For now, this is a no-op or we could delete the file.
        pass
